import React from "react"

export default function ReviewsTrend({ reviewTrend }) {
  const trendWidth=1100, trendHeight=410, trendLeft=52, trendRight=52, trendTop=22, trendBottom=70
  const plotWidth=trendWidth-trendLeft-trendRight, plotHeight=trendHeight-trendTop-trendBottom
  const maxCount=Math.max(1,...reviewTrend.map(p=>p.count))
  const x=i=>reviewTrend.length<=1?trendLeft+plotWidth/2:trendLeft+(i/(reviewTrend.length-1))*plotWidth
  const yAvg=v=>trendTop+plotHeight-((v-1)/4)*plotHeight
  const avgPath=reviewTrend.filter(p=>p.average!==null).map((p,i)=>{const n=reviewTrend.indexOf(p);return (i===0?"M":"L")+" "+x(n).toFixed(1)+" "+yAvg(p.average).toFixed(1)}).join(" ")
  const years=Array.from(reviewTrend.reduce((m,p,i)=>{const y=p.date.getFullYear();const g=m.get(y)||{year:y,firstIndex:i,lastIndex:i};g.lastIndex=i;m.set(y,g);return m},new Map()).values())
  return <section className="reviews-trend-card"><div className="reviews-trend-header"><div><h2 className="reviews-trend-title">Review performance over time</h2><p className="reviews-trend-subtitle">Quarterly review volume by source and combined average rating.</p></div><div className="reviews-trend-legend"><span className="reviews-trend-legend-item"><span className="reviews-trend-legend-dot reviews-trend-trustpilot-dot"/>Trustpilot</span><span className="reviews-trend-legend-item"><span className="reviews-trend-legend-dot reviews-trend-google-dot"/>Google</span><span className="reviews-trend-legend-item"><span className="reviews-trend-legend-dot reviews-trend-average-dot"/>Running average</span></div></div>{reviewTrend.length===0?<div className="reviews-trend-empty">No dated reviews are available to chart yet.</div>:<div className="reviews-trend-chart"><svg className="reviews-trend-svg" viewBox={"0 0 "+trendWidth+" "+trendHeight} preserveAspectRatio="none">{[0,.25,.5,.75,1].map(step=>{const y=trendTop+plotHeight-step*plotHeight;return <g key={step}><line className="reviews-trend-gridline" x1={trendLeft} x2={trendWidth-trendRight} y1={y} y2={y}/><text className="reviews-trend-axis" x={trendLeft-9} y={y+4} textAnchor="end">{Math.round(step*maxCount).toLocaleString("en-GB")}</text><text className="reviews-trend-axis" x={trendWidth-trendRight+9} y={y+4}>{(1+step*4).toFixed(1)}</text></g>})}{reviewTrend.map((p,i)=>{const xx=x(i),bw=Math.max(5,Math.min(18,plotWidth/Math.max(reviewTrend.length*1.8,1))),th=plotHeight*(p.trustpilot/maxCount),gh=plotHeight*(p.google/maxCount),bottom=trendTop+plotHeight;return <g key={p.key}>{p.trustpilot>0&&<rect className="reviews-trend-trustpilot-bar" x={xx-bw/2} y={bottom-th} width={bw} height={th} rx="2"/>}{p.google>0&&<rect className="reviews-trend-google-bar" x={xx-bw/2} y={bottom-th-gh} width={bw} height={gh} rx="2"/>}{p.average!==null&&<circle className="reviews-trend-average-point" cx={xx} cy={yAvg(p.average)} r="4"/>}<text className="reviews-trend-axis" x={xx} y={trendHeight-39} textAnchor="middle">{p.label.split(" ")[0]}</text></g>})}{reviewTrend.length>1&&avgPath&&<path className="reviews-trend-average-line" d={avgPath}/>} {years.slice(0,-1).map((g,i)=>{const n=years[i+1],xx=x((g.lastIndex+n.firstIndex)/2);return <line key={g.year} className="reviews-trend-gridline" x1={xx} x2={xx} y1={trendTop} y2={trendTop+plotHeight}/>})}{years.map(g=><text key={g.year} className="reviews-trend-axis" x={x((g.firstIndex+g.lastIndex)/2)} y={trendHeight-12} textAnchor="middle" style={{fontWeight:700}}>{g.year}</text>)}</svg></div>}</section>
}