import React,{useEffect,useRef,useState} from "react"
import {ArrowLeft,CalendarDays,Check,ChevronDown,Mail,MapPin,Pencil,Phone,Plus,UserRound,X} from "lucide-react"
import {supabase} from "../lib/supabase"
import EPVSCalculator from "../EPVSCalculator"
import WindowCosting from "../WindowCosting"
import {GenerateSolarContract} from "../contracts/GenerateSolarContract"
import ActionHistory from "../components/ActionHistory"
import AllocateBranch from "../components/AllocateBranch"

const card={background:"#fff",border:"1px solid #e2e5e8",borderRadius:9,boxSizing:"border-box"}
const link={border:0,background:"transparent",color:"#1684cf",cursor:"pointer",padding:0,fontFamily:"inherit",fontSize:10,fontWeight:600}
const menu={width:"100%",height:32,border:0,borderRadius:5,background:"transparent",color:"#333",cursor:"pointer",display:"flex",alignItems:"center",gap:8,padding:"0 9px",fontFamily:"inherit",fontSize:10,textAlign:"left"}
const primary={height:34,padding:"0 14px",border:0,borderRadius:6,background:"#2499ed",color:"#fff",cursor:"pointer",fontFamily:"inherit",fontSize:10,fontWeight:700}
const secondary={height:34,padding:"0 12px",border:"1px solid #d8dde1",borderRadius:6,background:"#fff",color:"#555",cursor:"pointer",fontFamily:"inherit",fontSize:10}

function normalise(v){return String(v||"").trim().toLowerCase()}
function isSold(v){return normalise(v)==="sold"}
function submittedBy(user){return String(user?.user_metadata?.full_name||user?.user_metadata?.name||"").trim()||user?.email||"Unknown"}
function date(v){if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})}
function solar(a){if(!a)return false;return [a.product,a.type,a.appointment_type,a.job_type,a.product_type,a.service].some(v=>normalise(v).includes("solar"))||!!a.epvs_calculation}
function resultStyle(v){const n=normalise(v);if(n.includes("sold"))return{background:"#dff4e6",color:"#137a3c"};if(n.includes("cancel")||n.includes("lost"))return{background:"#fbeaea",color:"#8b3333"};return{background:"#f2f4f6",color:"#59636c"}}

function InfoCard({title,Icon,action,children}){return <div style={{...card,padding:15}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,marginBottom:11}}><div style={{display:"flex",alignItems:"center",gap:7}}>{Icon&&<Icon size={14} color="#2499ed"/>}<span style={{fontSize:11,fontWeight:700,color:"#222"}}>{title}</span></div>{action}</div>{children}</div>}
function Row({label,value,Icon}){return <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,padding:"6px 0",borderBottom:"1px solid #f0f1f2"}}><span style={{fontSize:9,color:"#999"}}>{label}</span><span style={{display:"flex",alignItems:"center",gap:5,minWidth:0,fontSize:10,color:"#333",textAlign:"right"}}>{Icon&&<Icon size={11} color="#999"/>}<span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{value||"—"}</span></span></div>}
function Badge({value}){return <span style={{display:"inline-flex",alignItems:"center",padding:"5px 9px",borderRadius:6,fontSize:10,fontWeight:700,...resultStyle(value)}}>{value||"Not resulted"}</span>}
function CpsSummary({values}){const items=[["H",values.cps_h],["C",values.cps_c],["P",values.cps_p],["S",values.cps_s]];const all=items.every(x=>x[1]);return <><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8}}>{items.map(([l,a])=><div key={l} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:5}}><span style={{fontSize:9,fontWeight:700,color:"#59636c"}}>{l}</span><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:23,height:23,borderRadius:"50%",background:a?"#20a464":"#e8ecef",color:a?"#fff":"#9aa3aa"}}>{a?<Check size={13}/>:<X size={13}/>}</span></div>)}</div><div style={{marginTop:12,textAlign:"center",fontSize:10,fontWeight:700,color:all?"#159447":"#8a949c"}}>{all?"All complete":"Incomplete"}</div></>}
function SignaturePad({signature,setSignature}){const ref=useRef(null),drawing=useRef(false);const point=e=>{const c=ref.current;if(!c)return null;const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*(c.width/r.width),y:(e.clientY-r.top)*(c.height/r.height)}};const start=e=>{e.preventDefault();const c=ref.current,ctx=c?.getContext("2d");if(!c||!ctx)return;drawing.current=true;const p=point(e);if(!p)return;ctx.beginPath();ctx.moveTo(p.x,p.y);c.setPointerCapture?.(e.pointerId)};const draw=e=>{if(!drawing.current)return;e.preventDefault();const c=ref.current,ctx=c?.getContext("2d"),p=point(e);if(!c||!ctx||!p)return;ctx.lineWidth=2.2;ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="#10212b";ctx.lineTo(p.x,p.y);ctx.stroke();setSignature(c.toDataURL("image/png"))};const stop=e=>{drawing.current=false;try{ref.current?.releasePointerCapture?.(e.pointerId)}catch{}};const clear=()=>{const c=ref.current,ctx=c?.getContext("2d");if(!c||!ctx)return;ctx.clearRect(0,0,c.width,c.height);setSignature("")};return <div style={{marginTop:16}}><label style={{display:"block",fontSize:10,color:"#666",marginBottom:6}}>Customer Signature</label><div style={{border:"1px solid #d8dde1",borderRadius:6,background:"#fff",overflow:"hidden",touchAction:"none"}}><canvas ref={ref} width={900} height={240} onPointerDown={start} onPointerMove={draw} onPointerUp={stop} onPointerCancel={stop} style={{display:"block",width:"100%",height:150,cursor:"crosshair",touchAction:"none"}}/></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:6}}><span style={{fontSize:9,color:signature?"#6d757c":"#aaa"}}>{signature?"Signature captured":"Draw your signature above"}</span><button type="button" onClick={clear} style={link}>Clear signature</button></div></div>}

export default function AppointmentDetail({appointment,onBack,onUpdated,permissionLevel}){
 const canCps=Number(permissionLevel)>=4
 const [showResult,setShowResult]=useState(false),[showActions,setShowActions]=useState(false),[result,setResult]=useState(appointment?.result||appointment?.status||""),[signature,setSignature]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState(""),[confirming,setConfirming]=useState(false),[confirmError,setConfirmError]=useState(""),[cps,setCps]=useState({cps_h:appointment?.cps_h===true,cps_c:appointment?.cps_c===true,cps_p:appointment?.cps_p===true,cps_s:appointment?.cps_s===true}),[savingCps,setSavingCps]=useState(false),[cpsError,setCpsError]=useState(""),[epvs,setEpvs]=useState(appointment?.epvs_calculation||null)
 const isWindows=normalise(appointment?.job_type)==="windows",isSolar=solar(appointment),mapQuery=[appointment?.address,appointment?.postcode].filter(Boolean).join(", ")
 useEffect(()=>{setResult(appointment?.result||appointment?.status||"");setCps({cps_h:appointment?.cps_h===true,cps_c:appointment?.cps_c===true,cps_p:appointment?.cps_p===true,cps_s:appointment?.cps_s===true});setEpvs(appointment?.epvs_calculation||null)},[appointment])
 async function confirmAppointment(){if(!appointment?.appointment_row_id||confirming)return;setConfirming(true);setConfirmError("");let actionId=null;try{const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userError;const by=submittedBy(userData?.user),now=new Date().toISOString();const{data:action,error:actionError}=await supabase.from("action_runs").insert({action_type:"confirm_appointment",status:"running",entity_type:"appointment",entity_id:appointment.appointment_row_id,triggered_by:by,started_at:now,input_data:{appointment_row_id:appointment.appointment_row_id}}).select("id").single();if(actionError)throw actionError;actionId=action.id;const{data:updated,error:updateError}=await supabase.from("appointments").update({cps_c:true}).eq("appointment_row_id",appointment.appointment_row_id).select("*").single();if(updateError)throw updateError;const{error:actionUpdateError}=await supabase.from("action_runs").update({status:"completed",completed_at:new Date().toISOString(),output_data:{appointment_row_id:updated.appointment_row_id,cps_c:true}}).eq("id",actionId);if(actionUpdateError)throw actionUpdateError;setCps(v=>({...v,cps_c:true}));onUpdated?.(updated)}catch(e){console.error("Confirm Appointment action failed:",e);const msg=e?.message||"Unable to confirm appointment.";setConfirmError(msg);if(actionId)await supabase.from("action_runs").update({status:"failed",completed_at:new Date().toISOString(),error_message:msg}).eq("id",actionId)}finally{setConfirming(false)}}
 async function uploadSignature(){if(!signature)return null;const response=await fetch(signature),blob=await response.blob(),path=`appointments/${appointment.appointment_row_id}/signature.png`;const{error:e}=await supabase.storage.from("signatures").upload(path,blob,{contentType:"image/png",upsert:true});if(e)throw e;return path}
 async function saveResult(){if(!result)return;if(!appointment?.appointment_row_id){setError("This appointment does not have an appointment_row_id.");return}if(isSold(result)&&!signature){setError("A customer signature is required when marking the appointment as Sold.");return}setSaving(true);setError("");try{let signaturePath=null;if(isSold(result)&&signature)signaturePath=await uploadSignature();const{data,error:updateError}=await supabase.from("appointments").update({result,signature_path:signaturePath}).eq("appointment_row_id",appointment.appointment_row_id).select("*");if(updateError)throw updateError;if(!data?.length)throw new Error("No appointment was updated. Check that appointment_row_id matches a row in the appointments table.");const updated=data[0];onUpdated?.(updated);if(isSold(result)&&solar({...appointment,...updated})){if(!epvs)throw new Error("The appointment was saved as Sold, but no EPVS calculation is available. Please complete the EPVS calculation before generating the solar contract.");try{await GenerateSolarContract({appointment:updated,epvsCalculation:epvs,signaturePath})}catch(e){console.error("Error generating solar contract:",e);setError(`Appointment was saved as Sold, but the solar contract could not be generated: ${e?.message||String(e||"Unknown error")}`);return}}setShowResult(false);setSignature("")}catch(e){console.error("Error updating appointment:",e);setError(e?.message||"Unable to save result.")}finally{setSaving(false)}}
 function toggleCps(field){if(!canCps)return;setCps(v=>({...v,[field]:!v[field]}));setCpsError("")}
 async function saveCps(){if(!canCps)return;setSavingCps(true);setCpsError("");try{const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userError;const by=submittedBy(userData?.user),now=new Date().toISOString();const{data:action,error:actionError}=await supabase.from("action_runs").insert({action_type:"update_cps_status",status:"running",entity_type:"appointment",entity_id:appointment.appointment_row_id,triggered_by:by,started_at:now,input_data:{appointment_row_id:appointment.appointment_row_id,...cps}}).select("id").single();if(actionError)throw actionError;const{data:updated,error:updateError}=await supabase.from("appointments").update(cps).eq("appointment_row_id",appointment.appointment_row_id).select("*").single();if(updateError)throw updateError;const{error:actionUpdateError}=await supabase.from("action_runs").update({status:"completed",completed_at:new Date().toISOString(),output_data:{appointment_row_id:updated.appointment_row_id,cps_h:updated.cps_h,cps_c:updated.cps_c,cps_p:updated.cps_p,cps_s:updated.cps_s}}).eq("id",action.id);if(actionUpdateError)throw actionUpdateError;onUpdated?.(updated)}catch(e){console.error("Save CPS status failed:",e);setCpsError(e?.message||"Unable to save CPS status.")}finally{setSavingCps(false)}}
 function openResult(){setError("");setSignature("");setShowActions(false);setShowResult(true)}
 if(!appointment)return null
 return <section style={{width:"100%",boxSizing:"border-box"}}>
  <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",gap:20,marginBottom:18}}>
   <div><button type="button" onClick={onBack} style={{border:0,background:"transparent",color:"#66717b",cursor:"pointer",padding:0,display:"flex",alignItems:"center",gap:6,fontFamily:"inherit",fontSize:10,marginBottom:12}}><ArrowLeft size={14}/>Back to appointments</button><h1 style={{margin:0,fontSize:24,lineHeight:1.15,color:"#10233f",fontWeight:750}}>{appointment.name||"Unnamed customer"}</h1><div style={{display:"flex",alignItems:"center",flexWrap:"wrap",gap:8,marginTop:7,fontSize:12,color:"#66717b"}}><span>{date(appointment.appointment_date)}</span><span>•</span><span>{appointment.job_type||appointment.product||appointment.type||"Appointment"}</span>{result&&<Badge value={result}/>}</div></div>
   <div style={{position:"relative",flexShrink:0}}><button type="button" onClick={()=>setShowActions(v=>!v)} style={{...primary,height:36}}>Actions <ChevronDown size={13}/></button>{showActions&&<div style={{position:"absolute",right:0,top:42,width:195,background:"#fff",border:"1px solid #e1e5e8",borderRadius:8,boxShadow:"0 12px 30px rgba(0,0,0,.12)",padding:5,zIndex:50}}>{!appointment.cps_c&&<button type="button" onClick={()=>{setShowActions(false);confirmAppointment()}} disabled={confirming} style={menu}><Check size={13}/>{confirming?"Confirming...":"Confirm appointment"}</button>}{appointment.cps_c&&<div style={{padding:"2px 0"}}><AllocateBranch appointment={appointment} onUpdated={onUpdated} menuItem/></div>}<button type="button" onClick={openResult} style={menu}><Plus size={13}/>Set result</button><button type="button" onClick={()=>setShowActions(false)} style={menu}><Pencil size={13}/>Edit appointment</button></div>}</div>
  </div>
  {confirmError&&<div style={{marginBottom:14,padding:"9px 10px",background:"#fbeaea",color:"#8b3333",borderRadius:6,fontSize:10}}>{confirmError}</div>}
  <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 320px",gap:18,alignItems:"start"}}>
   <main style={{minWidth:0}}>
    {isWindows&&<WindowCosting appointment={appointment} onUpdated={onUpdated}/>} 
    {!isWindows&&isSolar&&<div style={{...card,padding:18}}><div style={{marginBottom:12}}><h2 style={{margin:0,fontSize:18,color:"#10233f"}}>EPVS Calculator</h2><p style={{margin:"5px 0 0",fontSize:11,color:"#888"}}>Complete the EPVS calculation for this solar appointment.</p></div><EPVSCalculator appointment={appointment} onCalculationChange={setEpvs}/></div>}
    <div style={{marginTop:18,...card,padding:17}}><h2 style={{margin:0,fontSize:18,color:"#10233f"}}>Activity</h2><div style={{marginTop:12}}><ActionHistory entityType="appointment" entityId={appointment.appointment_row_id}/></div></div>
   </main>
   <aside style={{display:"flex",flexDirection:"column",gap:14,minWidth:0}}>
    <div style={{...card,overflow:"hidden",background:"#eef1f3"}}><div style={{height:250}}>{mapQuery?<iframe title="Customer location" width="100%" height="100%" style={{border:0,display:"block"}} loading="lazy" src={`https://www.google.com/maps?q=${encodeURIComponent(mapQuery)}&output=embed`}/>:<div style={{height:"100%",display:"flex",alignItems:"center",justifyContent:"center",color:"#888",fontSize:10}}>No postcode available</div>}</div>{mapQuery&&<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(mapQuery)}`} target="_blank" rel="noreferrer" style={{display:"flex",alignItems:"center",justifyContent:"center",gap:5,margin:"-48px 12px 12px",position:"relative",height:36,background:"#fff",borderRadius:7,color:"#1679bd",fontSize:10,fontWeight:700,textDecoration:"none",boxShadow:"0 3px 12px rgba(0,0,0,.12)"}}><MapPin size={13}/>Open in Maps</a>}</div>
    <InfoCard title="Customer" Icon={UserRound} action={<button type="button" style={link}>Edit</button>}><Row label="Name" value={appointment.name}/><Row label="Phone" value={appointment.phone} Icon={appointment.phone?Phone:null}/><Row label="Email" value={appointment.email} Icon={appointment.email?Mail:null}/><Row label="Postcode" value={appointment.postcode} Icon={appointment.postcode?MapPin:null}/></InfoCard>
    <InfoCard title="Appointment" Icon={CalendarDays} action={<button type="button" style={link}>Edit</button>}><Row label="Date" value={date(appointment.appointment_date)}/><Row label="Job type" value={appointment.job_type}/><Row label="Type" value={appointment.product||appointment.type||appointment.appointment_type}/><Row label="Sales Rep" value={appointment.rep_allocated}/></InfoCard>
    <InfoCard title="Result" Icon={Check}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><span style={{fontSize:10,color:"#888"}}>Current result</span><Badge value={result}/></div></InfoCard>
    {canCps&&<InfoCard title="CPS Status" Icon={Check} action={<span style={{fontSize:9,color:"#999"}}>Permission 4+</span>}><CpsSummary values={cps}/><div style={{marginTop:12,display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6}}>{[["cps_h","H"],["cps_c","C"],["cps_p","P"],["cps_s","S"]].map(([f,l])=><button key={f} type="button" onClick={()=>toggleCps(f)} style={{height:26,border:"1px solid #dce2e6",borderRadius:5,background:cps[f]?"#eef8ff":"#fff",color:cps[f]?"#1679bd":"#7b858d",cursor:"pointer",fontSize:9,fontWeight:700}}>{l}</button>)}</div><button type="button" onClick={saveCps} disabled={savingCps} style={{...primary,width:"100%",height:31,marginTop:8,opacity:savingCps ? 0.65 : 1}}>{savingCps?"Saving...":"Save CPS status"}</button>{cpsError&&<div style={{marginTop:8,padding:8,background:"#fbeaea",borderRadius:6,color:"#8b3333",fontSize:9}}>{cpsError}</div>}</InfoCard>}
   </aside>
  </div>
  {showResult&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.35)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000,padding:20}}><div style={{width:420,maxHeight:"90vh",overflowY:"auto",background:"#fff",borderRadius:10,padding:20,boxShadow:"0 20px 60px rgba(0,0,0,.25)"}}><h3 style={{margin:"0 0 15px",fontSize:15}}>Set Appointment Result</h3><label style={{display:"block",fontSize:10,color:"#666",marginBottom:6}}>Result</label><select value={result} onChange={e=>{const v=e.target.value;setResult(v);if(!isSold(v))setSignature("")}} style={{width:"100%",height:36,border:"1px solid #d8dde1",borderRadius:6,padding:"0 9px",fontFamily:"inherit",fontSize:11,background:"#fff"}}><option value="">Select result...</option><option value="Sold">Sold</option><option value="No Sale">No Sale</option><option value="Cancelled">Cancelled</option></select>{isSold(result)&&<SignaturePad signature={signature} setSignature={setSignature}/>} {error&&<div style={{marginTop:12,padding:10,background:"#fbeaea",color:"#8b3333",borderRadius:6,fontSize:10,lineHeight:1.5}}>{error}</div>}<div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:18}}><button type="button" onClick={()=>{setShowResult(false);setSignature("");setError("")}} style={secondary}>Cancel</button><button type="button" onClick={saveResult} disabled={saving} style={{...primary,opacity:saving ? 0.65 : 1}}>{saving?"Saving...":"Save Result"}</button></div></div></div>}
 </section>
}
