import React, { useEffect, useMemo, useState } from "react"
import { ChevronDown } from "lucide-react"
import { supabase } from "./lib/supabase"

const EMPTY_FORM = { location:"", unitType:"", width:"", height:"", colour:"", shape:"", finish:"", glass:"", style:"", openers:0, fixed:0, handle:"", extras:"" }
const inputStyle={width:"100%",height:"36px",padding:"0 10px",border:"1px solid #d8dde1",borderRadius:"6px",background:"#fff",color:"#222",fontFamily:"inherit",fontSize:"11px",boxSizing:"border-box",outline:"none"}
const selectStyle={...inputStyle}
const SIZE_MATRIX_DIMENSIONS=[500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,2250,2500,2750,3000,3250]
const SIZE_MATRIX={
500:["A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","B"],
600:["A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","A","B","B","B"],
700:["A","A","A","A","A","A","A","A","A","A","A","A","A","B","B","B","B","B","B","B","B"],
800:["A","A","A","A","A","A","A","A","A","A","A","A","A","B","B","B","B","B","B","B","C"],
900:["A","A","A","A","A","A","A","A","A","A","B","B","B","B","B","B","B","B","B","C","C"],
1000:["A","A","A","A","A","B","B","B","B","B","B","B","B","B","B","B","B","C","C","C"],
1100:["A","A","A","A","A","B","B","B","B","B","B","B","B","B","B","B","B","C","C","C"],
1200:["A","A","A","A","A","B","B","B","B","B","B","B","B","B","B","C","C","C","C","D"],
1300:["A","A","A","A","A","B","B","B","B","B","B","B","B","C","C","C","C","C","C","C","D"],
1400:["A","A","A","A","A","B","B","B","B","B","C","C","C","C","C","C","C","C","C","C","D"],
1500:["A","A","A","A","B","B","B","B","B","C","C","C","C","C","C","D","D","D","D"],
1600:["A","A","A","A","B","B","B","B","B","C","C","C","C","C","D","D","D","D","D","E"],
1700:["A","A","A","B","B","B","B","B","B","C","C","C","C","C","D","D","D","D","D","E"],
1800:["A","A","A","B","B","B","B","B","C","C","C","C","C","C","D","D","D","D","D","E","E"],
1900:["A","A","A","B","B","B","B","B","C","C","C","C","D","D","D","D","D","E","E","E","E"],
2000:["A","A","A","B","B","B","B","C","C","C","C","D","D","D","D","D","E","E","E","E","F"],
2250:["A","A","B","B","B","B","B","C","C","C","C","D","D","D","D","E","E","E","E","F","F"],
2500:["A","B","B","B","B","B","C","C","C","C","D","D","D","D","D","E","E","F","G","G","G"],
2750:["A","B","B","B","B","C","C","C","C","D","D","D","D","D","D","E","E","E","F","G","G"],
3000:["B","B","B","B","C","C","C","C","C","D","D","D","D","E","E","E","F","F","G","H","H"],
3250:["B","B","B","C","C","C","C","D","D","D","D","D","E","E","E","F","F","G","G","H","H"]}
function roundUpToMatrixSize(v){const n=Number(v);if(!Number.isFinite(n)||n<=0)return null;return SIZE_MATRIX_DIMENSIONS.find(d=>n<=d)||null}
function getSizeChoice(w,h){const rw=roundUpToMatrixSize(w),rh=roundUpToMatrixSize(h);if(!rw||!rh)return null;const row=SIZE_MATRIX[rh],i=SIZE_MATRIX_DIMENSIONS.indexOf(rw);return row&&i>=0?{choice:row[i],roundedWidth:rw,roundedHeight:rh}:null}
function normalise(v){return String(v??"").trim().toLowerCase()}
function Field({label,required,children}){return <label style={{display:"block"}}><span style={{display:"block",marginBottom:"6px",fontSize:"10px",fontWeight:700,color:"#59636c"}}>{label}{required&&<span style={{color:"#2499ed"}}> *</span>}</span>{children}</label>}
function getChoices(rows,categories,type){const cats=new Set(categories.map(normalise)),t=normalise(type);return Array.from(new Set(rows.filter(r=>cats.has(normalise(r.category))&&(!normalise(r.unit_type)||!t||normalise(r.unit_type)===t)).map(r=>String(r.choice??"").trim()).filter(Boolean)))}
function getSizeValue(rows,choice,type){if(!choice)return null;const t=normalise(type);const r=rows.find(x=>["size","size choice","size_choice"].includes(normalise(x.category))&&normalise(x.choice)===normalise(choice)&&(!normalise(x.unit_type)||!t||normalise(x.unit_type)===t));if(!r)return null;const v=Number(r.value);return Number.isFinite(v)?v:null}
function getChoiceValue(rows,category,choice,type){if(!choice)return 0;const t=normalise(type),r=rows.find(x=>normalise(x.category)===normalise(category)&&normalise(x.choice)===normalise(choice)&&(!normalise(x.unit_type)||!t||normalise(x.unit_type)===t));const v=Number(r?.value);return Number.isFinite(v)?v:0}
function calculateUnitValues({choices,unitType,sizeValue,colour,shape,finish,style,glass,extras,openers,fixed}){if(unitType!=="Window")return{colourValue:0,shapeValue:0,finishValue:0,styleValue:0,glassValue:0,extrasValue:0,fixOpenersValue:0,discountable:null};const size=Number(sizeValue)||0,colourValue=getChoiceValue(choices,"colour",colour,unitType),shapeValue=getChoiceValue(choices,"shape",shape,unitType),finishValue=getChoiceValue(choices,"finish",finish,unitType),styleValue=getChoiceValue(choices,"style",style,unitType),glassValue=getChoiceValue(choices,"glass",glass,unitType),extrasValue=getChoiceValue(choices,"extras",extras,unitType),o=Number(openers)||0,f=Number(fixed)||0,x=!style||normalise(style)==="fixed unit"?0:250,fixOpenersValue=o*360+(f-1)*110-x,discountable=(size+finishValue+styleValue+fixOpenersValue+extrasValue)*colourValue*shapeValue+glassValue;return{colourValue,shapeValue,finishValue,styleValue,glassValue,extrasValue,fixOpenersValue,discountable:Number.isFinite(discountable)?discountable:0}}
function mapDatabaseUnit(row,index){return{id:row.UUID,unitNumber:index+1,location:row.location??"",unitType:row.unit_type??"",width:Number(row.width)||0,height:Number(row.height)||0,sizeChoice:row.size_choice??null,sizeValue:row.size_value!=null?Number(row.size_value):null,colour:row.colour_choice??"",shape:row.shape_choice??"",finish:row.finish_choice??"",glass:row.glass_choice??"",style:row.style_choice??"",openers:Number(row.openers_choice)||0,fixed:Number(row.fixed_choice)||0,handle:row.handle_choice??"",extras:row.extras_choice??"",createdBy:row.created_by??null,colourValue:row.colour_value!=null?Number(row.colour_value):null,shapeValue:row.shape_value!=null?Number(row.shape_value):null,finishValue:row.finish_value!=null?Number(row.finish_value):null,styleValue:row.style_value!=null?Number(row.style_value):null,glassValue:row.glass_value!=null?Number(row.glass_value):null,fixOpenersValue:row.fix_openers_value!=null?Number(row.fix_openers_value):null,discountable:row.discountable!=null?Number(row.discountable):null,nonDiscountable:row.non_discountable!=null?Number(row.non_discountable):null}}

export default function WindowCosting({appointment}){
 const [units,setUnits]=useState([]),[showForm,setShowForm]=useState(false),[editingUnit,setEditingUnit]=useState(null),[openMenu,setOpenMenu]=useState(null),[form,setForm]=useState({...EMPTY_FORM}),[choices,setChoices]=useState([]),[loadingChoices,setLoadingChoices]=useState(false),[loadingUnits,setLoadingUnits]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[expandedUnits,setExpandedUnits]=useState({})
 const isWindows=normalise(appointment?.job_type)==="windows",appointmentId=appointment?.appointment_row_id??appointment?.appointment_id??appointment?.id
 useEffect(()=>{if(!isWindows){setChoices([]);return}let cancelled=false;async function load(){setLoadingChoices(true);const{data,error}=await supabase.from("unit_choices").select("unit_type, category, charge_type, choice, value_type, value").order("category").order("choice");if(cancelled)return;if(error){setError(error.message||"Unable to load window choices.");setChoices([])}else setChoices(data||[]);setLoadingChoices(false)}load();return()=>{cancelled=true}},[isWindows])
 useEffect(()=>{if(!isWindows||!appointmentId){setUnits([]);return}let cancelled=false;async function load(){setLoadingUnits(true);const{data,error}=await supabase.from("units").select("*").eq("appointment_id",String(appointmentId)).order("created_date",{ascending:true});if(cancelled)return;if(error){setError(error.message||"Unable to load window units.");setUnits([])}else setUnits((data||[]).map((r,i)=>mapDatabaseUnit(r,i)));setLoadingUnits(false)}load();return()=>{cancelled=true}},[isWindows,appointmentId])
 const typeOptions=useMemo(()=>Array.from(new Set(choices.map(r=>String(r.unit_type??"").trim()).filter(Boolean))),[choices])
 const options=useMemo(()=>({colour:getChoices(choices,["colour"],form.unitType),shape:getChoices(choices,["shape"],form.unitType),finish:getChoices(choices,["finish"],form.unitType),glass:getChoices(choices,["glass","glass optionals"],form.unitType),style:getChoices(choices,["style"],form.unitType),handle:getChoices(choices,["handle"],form.unitType),extras:getChoices(choices,["extras"],form.unitType)}),[choices,form.unitType])
 const calculatedSize=useMemo(()=>form.unitType!=="Window"?null:getSizeChoice(form.width,form.height),[form.width,form.height,form.unitType])
 const calculatedSizeValue=useMemo(()=>form.unitType!=="Window"||!calculatedSize?null:getSizeValue(choices,calculatedSize.choice,form.unitType),[choices,calculatedSize,form.unitType])
 function updateForm(field,value){setForm(c=>({...c,[field]:value}));setError("")}
 function openForm(unit=null){setOpenMenu(null);setEditingUnit(unit);setForm(unit?{location:unit.location||"",unitType:unit.unitType||"",width:String(unit.width||""),height:String(unit.height||""),colour:unit.colour||"",shape:unit.shape||"",finish:unit.finish||"",glass:unit.glass||"",style:unit.style||"",openers:unit.openers||0,fixed:unit.fixed||0,handle:unit.handle||"",extras:unit.extras||""}:{...EMPTY_FORM,unitType:typeOptions[0]||""});setError("");setShowForm(true)}
 function closeForm(){if(saving)return;setShowForm(false);setEditingUnit(null);setForm({...EMPTY_FORM});setError("")}
 function toggleUnit(id){setExpandedUnits(c=>({...c,[id]:!c[id]}))}
 async function saveUnit(event){event.preventDefault();if(saving)return;if(!form.location.trim())return setError("Please enter a location.");if(!form.unitType)return setError("Please select a type.");if(!form.width||!form.height)return setError("Please enter the width and height.");if(form.unitType==="Window"){if(!calculatedSize)return setError("The entered dimensions are outside the available size matrix. Maximum size is 3250mm.");if(calculatedSizeValue===null){setError("No Size value was found in unit_choices for Size Choice "+calculatedSize.choice+" and type "+form.unitType+".");return}}if(!appointmentId)return setError("Unable to save the unit because no appointment ID was found.");setSaving(true);setError("");try{const values=calculateUnitValues({choices,unitType:form.unitType,sizeValue:calculatedSizeValue,colour:form.colour,shape:form.shape,finish:form.finish,style:form.style,glass:form.glass,extras:form.extras,openers:form.openers,fixed:form.fixed});const{data:{user}}=await supabase.auth.getUser();const data={appointment_id:String(appointmentId),location:form.location.trim(),created_date:editingUnit?undefined:new Date().toISOString(),created_by:user?.email||null,unit_type:form.unitType,size_choice:form.unitType==="Window"?calculatedSize?.choice||null:null,height:Number(form.height),width:Number(form.width),size_value:form.unitType==="Window"&&calculatedSizeValue!==null?Math.round(calculatedSizeValue):null,colour_choice:form.colour||null,shape_choice:form.shape||null,finish_choice:form.finish||null,style_choice:form.style||null,glass_choice:form.glass||null,handle_choice:form.handle||null,fixed_choice:form.unitType==="Window"?String(Number(form.fixed)||0):null,openers_choice:form.unitType==="Window"?String(Number(form.openers)||0):null,extras_choice:form.extras||null,colour_value:values.colourValue,shape_value:values.shapeValue,finish_value:values.finishValue,style_value:values.styleValue,glass_value:values.glassValue,fix_openers_value:values.fixOpenersValue,discountable:values.discountable};if(!editingUnit)data.UUID=crypto.randomUUID();else delete data.created_date;const result=editingUnit?await supabase.from("units").update(data).eq("UUID",editingUnit.id).select("*").single():await supabase.from("units").insert(data).select("*").single();if(result.error)throw new Error(result.error.message||"Unable to save unit.");setUnits(c=>editingUnit?c.map(u=>u.id===editingUnit.id?mapDatabaseUnit(result.data,u.unitNumber-1):u):[...c,mapDatabaseUnit(result.data,c.length)]);closeForm()}catch(err){console.error(err);setError(err?.message||"Unable to save unit.")}finally{setSaving(false)}}
 async function duplicateUnit(unit){setOpenMenu(null);if(!unit)return;try{const{data:{user}}=await supabase.auth.getUser();const copy={appointment_id:String(appointmentId),location:(unit.location||"")+" (Copy)",created_date:new Date().toISOString(),created_by:user?.email||null,unit_type:unit.unitType,size_choice:unit.sizeChoice,height:unit.height,width:unit.width,size_value:unit.sizeValue,colour_choice:unit.colour||null,shape_choice:unit.shape||null,finish_choice:unit.finish||null,style_choice:unit.style||null,glass_choice:unit.glass||null,handle_choice:unit.handle||null,fixed_choice:String(unit.fixed||0),openers_choice:String(unit.openers||0),extras_choice:unit.extras||null,colour_value:unit.colourValue,shape_value:unit.shapeValue,finish_value:unit.finishValue,style_value:unit.styleValue,glass_value:unit.glassValue,fix_openers_value:unit.fixOpenersValue,discountable:unit.discountable,non_discountable:unit.nonDiscountable,UUID:crypto.randomUUID()};const{data,error}=await supabase.from("units").insert(copy).select("*").single();if(error)throw error;setUnits(c=>[...c,mapDatabaseUnit(data,c.length)])}catch(err){console.error(err);setError(err?.message||"Unable to duplicate unit.")}}
 async function deleteUnit(unit){setOpenMenu(null);if(!unit)return;if(!window.confirm("Delete this unit?"))return;if(unit.id){const{error}=await supabase.from("units").delete().eq("UUID",unit.id);if(error){setError(error.message||"Unable to delete unit.");return}}setUnits(c=>c.filter(x=>x.id!==unit.id).map((x,i)=>({...x,unitNumber:i+1})));setExpandedUnits(c=>{const n={...c};delete n[unit.id];return n})}
 const renderSelect=(field,label,list)=>!list?.length?null:<Field label={label}><select value={form[field]} onChange={e=>updateForm(field,e.target.value)} style={{...selectStyle,color:form[field]?"#222":"#777"}} disabled={loadingChoices}><option value="">Select {label.toLowerCase()}...</option>{list.map(o=><option key={o} value={o}>{o}</option>)}</select></Field>
 if(!isWindows)return null
 const gridColumns="1.2fr .9fr 1fr 1fr .9fr .45fr .45fr .8fr .9fr .9fr 30px 32px";const money=v=>v!=null?"£"+Math.round(Number(v)).toLocaleString("en-GB"):"—"
 return <section style={{width:"100%",marginTop:"24px"}}>
  <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:"12px"}}><div><h2 style={{margin:0,fontSize:"18px",fontWeight:700,color:"#222"}}>Windows</h2><p style={{margin:"5px 0 0",fontSize:"11px",color:"#888"}}>Add and configure individual window units.</p></div><button type="button" onClick={()=>openForm()} style={{height:"34px",padding:"0 14px",border:0,borderRadius:"7px",background:"#2499ed",color:"#fff",cursor:"pointer",fontFamily:"inherit",fontSize:"10px",fontWeight:700}}>+ Add Unit</button></div>
  {error&&!showForm&&<div style={{marginBottom:"10px",padding:"9px 10px",borderRadius:"6px",background:"#fbeaea",color:"#8b3333",fontSize:"10px"}}>{error}</div>}
  {loadingUnits?<div style={{padding:"24px",border:"1px dashed #d8dde1",borderRadius:"8px",background:"#fafbfc",textAlign:"center",fontSize:"10px",color:"#888"}}>Loading window units...</div>:units.length===0?<div style={{padding:"24px",border:"1px dashed #d8dde1",borderRadius:"8px",background:"#fafbfc",textAlign:"center"}}><div style={{fontSize:"11px",fontWeight:700,color:"#555"}}>No window units added</div><div style={{marginTop:"4px",fontSize:"10px",color:"#999"}}>Click “Add Unit” to add the first window.</div></div>:<div style={{border:"1px solid #e2e5e8",borderRadius:"8px",background:"#fff",overflow:"hidden"}}>
   <div style={{display:"grid",gridTemplateColumns:gridColumns,gap:"10px",alignItems:"center",padding:"10px 12px",borderBottom:"1px solid #e5e7e9",background:"#fafbfc",fontSize:"8px",fontWeight:700,color:"#6d757c",textTransform:"uppercase"}}><span>Location</span><span>Type</span><span>Size</span><span>Style</span><span>Colour</span><span>F</span><span>O</span><span>Size Choice</span><span>Discountable</span><span>NonDiscountable</span><span></span><span></span></div>
   {units.map(unit=>{const expanded=!!expandedUnits[unit.id],menuOpen=openMenu===unit.id;return <div key={unit.id} style={{borderBottom:"1px solid #eef0f2",position:"relative"}}>
    <div style={{display:"grid",gridTemplateColumns:gridColumns,gap:"10px",alignItems:"center",padding:"11px 12px",fontSize:"10px",color:"#333"}}>
     <strong>{unit.location}</strong><span>{unit.unitType||"—"}</span><span>{unit.width} × {unit.height}</span><span>{unit.style||"—"}</span><span>{unit.colour||"—"}</span><span>{unit.fixed??0}</span><span>{unit.openers??0}</span><span>{unit.sizeChoice||"—"}</span><strong>{money(unit.discountable)}</strong><strong>{money(unit.nonDiscountable)}</strong>
     <button type="button" onClick={()=>toggleUnit(unit.id)} title={expanded?"Collapse unit":"Expand unit"} aria-expanded={expanded} style={{border:0,background:"transparent",color:"#707980",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",padding:0,width:30,height:26}}><ChevronDown size={15} style={{transform:expanded?"rotate(0deg)":"rotate(-90deg)",transition:"transform .15s ease"}}/></button>
     <button type="button" onClick={()=>setOpenMenu(menuOpen?null:unit.id)} title="Unit actions" aria-expanded={menuOpen} style={{border:0,background:"transparent",color:menuOpen?"#2499ed":"#888",cursor:"pointer",fontSize:"16px",padding:0,width:32,height:26,lineHeight:1}}>⋯</button>
     {menuOpen&&<div style={{position:"absolute",right:"12px",top:"43px",zIndex:20,minWidth:"155px",padding:"5px",background:"#fff",border:"1px solid #e1e5e8",borderRadius:"8px",boxShadow:"0 8px 24px rgba(0,0,0,.12)"}}>
      <button type="button" onClick={()=>openForm(unit)} style={{display:"block",width:"100%",padding:"8px 10px",border:0,borderRadius:"5px",background:"transparent",textAlign:"left",fontSize:"10px",color:"#333",cursor:"pointer"}}>Edit Unit</button>
      <button type="button" onClick={()=>{setOpenMenu(null);toggleUnit(unit.id)}} style={{display:"block",width:"100%",padding:"8px 10px",border:0,borderRadius:"5px",background:"transparent",textAlign:"left",fontSize:"10px",color:"#333",cursor:"pointer"}}>{expanded?"Collapse Unit":"Toggle Unit"}</button>
      <button type="button" onClick={()=>duplicateUnit(unit)} style={{display:"block",width:"100%",padding:"8px 10px",border:0,borderRadius:"5px",background:"transparent",textAlign:"left",fontSize:"10px",color:"#333",cursor:"pointer"}}>Duplicate Unit</button>
      <button type="button" onClick={()=>deleteUnit(unit)} style={{display:"block",width:"100%",padding:"8px 10px",border:0,borderRadius:"5px",background:"transparent",textAlign:"left",fontSize:"10px",color:"#c23b3b",cursor:"pointer"}}>Delete Unit</button>
     </div>}
    </div>
    {expanded&&<div style={{padding:"14px 12px 16px",background:"#f8fafc",borderTop:"1px solid #eef0f2"}}><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:"10px 18px"}}>{[["Dimensions",`${unit.width} × ${unit.height} mm"],["Location",unit.location],["Type",unit.unitType],["Size Choice",unit.sizeChoice],["Size Value",unit.sizeValue],["Colour",unit.colour],["Colour Value",unit.colourValue],["Shape",unit.shape],["Shape Value",unit.shapeValue],["Finish",unit.finish],["Finish Value",unit.finishValue],["Style",unit.style],["Style Value",unit.styleValue],["Glass",unit.glass],["Glass Value",unit.glassValue],["Handle",unit.handle],["Openers",unit.openers],["Fixed",unit.fixed],["Fix/Openers Value",unit.fixOpenersValue],["Extras",unit.extras],["Discountable",money(unit.discountable)],["NonDiscountable",money(unit.nonDiscountable)]].map(([label,value])=><div key={label}><div style={{fontSize:"8px",fontWeight:700,textTransform:"uppercase",color:"#8a949c",marginBottom:"3px"}}>{label}</div><div style={{fontSize:"10px",fontWeight:600,color:"#333",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{value!=null&&value!==""?String(value):"—"}</div></div>)}</div></div>}
   </div>})}
   <div style={{display:"grid",gridTemplateColumns:gridColumns,gap:"10px",alignItems:"center",padding:"12px",background:"#f4f7f9",borderTop:"2px solid #e2e5e8",fontSize:"10px",fontWeight:700,color:"#222"}}><span style={{gridColumn:"1 / span 8"}}>Total</span><strong>{money(units.reduce((t,u)=>t+(Number(u.discountable)||0),0))}</strong><strong>{money(units.reduce((t,u)=>t+(Number(u.nonDiscountable)||0),0))}</strong><span></span><span></span></div>
  </div>}
  {showForm&&<div style={{position:"fixed",inset:0,zIndex:1100,background:"rgba(0,0,0,.35)",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px"}}><form onSubmit={saveUnit} style={{width:"680px",maxWidth:"100%",maxHeight:"90vh",overflowY:"auto",background:"#fff",borderRadius:"10px",boxShadow:"0 20px 60px rgba(0,0,0,.25)"}}>
   <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"17px 20px",borderBottom:"1px solid #e6e8ea"}}><div><h3 style={{margin:0,fontSize:"15px",color:"#222"}}>{editingUnit?"Edit Window Unit":"Add Window Unit"}</h3><p style={{margin:"4px 0 0",fontSize:"10px",color:"#888"}}>{editingUnit?"Update the details for this unit.":"Enter the details for this individual unit."}</p></div><button type="button" onClick={closeForm} disabled={saving} style={{border:0,background:"transparent",color:"#777",cursor:saving?"default":"pointer",fontSize:"20px",lineHeight:1}}>×</button></div>
   <div style={{padding:"20px"}}><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:"15px"}}><Field label="Location" required><input value={form.location} onChange={e=>updateForm("location",e.target.value)} placeholder="e.g. Living room" style={inputStyle} autoFocus/></Field>{typeOptions.length>0&&<Field label="Type" required><select value={form.unitType} onChange={e=>updateForm("unitType",e.target.value)} style={selectStyle} disabled={loadingChoices}><option value="">Select type...</option>{typeOptions.map(o=><option key={o} value={o}>{o}</option>)}</select></Field>}<Field label="Width (mm)" required><input type="number" min="1" value={form.width} onChange={e=>updateForm("width",e.target.value)} placeholder="e.g. 960" style={inputStyle}/></Field><Field label="Height (mm)" required><input type="number" min="1" value={form.height} onChange={e=>updateForm("height",e.target.value)} placeholder="e.g. 1440" style={inputStyle}/></Field></div>
    <div style={{height:"2px",background:"#2499ed",opacity:.25,margin:"22px 0",borderRadius:"2px"}}/>{form.unitType==="Window"&&calculatedSize&&<div style={{marginBottom:"15px",padding:"10px 12px",border:"1px solid #dfe5ea",borderRadius:"7px",background:"#f8fafc",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><div style={{fontSize:"10px",fontWeight:700,color:"#59636c"}}>Size Choice</div><div style={{marginTop:"3px",fontSize:"9px",color:"#89939c"}}>Rounded up to {calculatedSize.roundedWidth} × {calculatedSize.roundedHeight} mm</div></div><div style={{fontSize:"20px",fontWeight:800,color:"#2499ed"}}>{calculatedSize.choice}</div></div>}
    <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:"15px"}}>{renderSelect("colour","Colour",options.colour)}{renderSelect("shape","Shape",options.shape)}{renderSelect("finish","Finish",options.finish)}{renderSelect("glass","Glass",options.glass)}{renderSelect("style","Style",options.style)}{form.unitType==="Window"&&<Field label="Number of Openers"><input type="number" min="0" step="1" value={form.openers} onChange={e=>updateForm("openers",e.target.value)} style={inputStyle}/></Field>}{form.unitType==="Window"&&<Field label="Number of Fixed"><input type="number" min="0" step="1" value={form.fixed} onChange={e=>updateForm("fixed",e.target.value)} style={inputStyle}/></Field>}{renderSelect("handle","Handle",options.handle)}{renderSelect("extras","Extras",options.extras)}</div>
    {loadingChoices&&<div style={{marginTop:"14px",fontSize:"10px",color:"#888"}}>Loading window choices...</div>}{form.unitType==="Window"&&calculatedSize&&calculatedSizeValue!==null&&<div style={{marginTop:"14px",fontSize:"10px",color:"#89939c"}}>Size {calculatedSize.choice} value: {calculatedSizeValue}</div>}{error&&<div style={{marginTop:"14px",padding:"9px 10px",borderRadius:"6px",background:"#fbeaea",color:"#8b3333",fontSize:"10px"}}>{error}</div>}
   </div><div style={{display:"flex",justifyContent:"flex-end",gap:"8px",padding:"13px 20px",borderTop:"1px solid #e6e8ea",background:"#fafbfc"}}><button type="button" onClick={closeForm} disabled={saving} style={{height:"34px",padding:"0 13px",border:"1px solid #d8dde1",borderRadius:"6px",background:"#fff",color:"#555",cursor:saving?"default":"pointer",fontFamily:"inherit",fontSize:"10px",fontWeight:600}}>Cancel</button><button type="submit" disabled={saving} style={{height:"34px",padding:"0 15px",border:0,borderRadius:"6px",background:saving?"#9acff5":"#2499ed",color:"#fff",cursor:saving?"default":"pointer",fontFamily:"inherit",fontSize:"10px",fontWeight:700}}>{saving?"Saving...":editingUnit?"Save Changes":"Add Unit"}</button></div>
  </form></div>}
 </section>
}